version: '3.7'

networks:
  app-tier:
    name: app-tier
    driver: bridge

services:
  etcd:
    image: bitnami/etcd:3.5.14
    container_name: etcd-server
    networks:
      - app-tier
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
